config/routes.rb
Rails.application.routes.draw do
  root 'pages#home' # Home page
  get '/about', to: 'pages#about' # About Me page
  get '/work', to: 'pages#work' # My Work page
  get '/contact', to: 'pages#contact' # Contact Me page
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <li><a href="<%= root_path %>">Home</a></li>
        <li><a href="<%= about_path %>">About Me</a></li>
        <li><a href="<%= work_path %>">My Work</a></li>
        <li><a href="<%= contact_path %>">Contact Me</a></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>Comp sci student</p>

app/views/pages/contact.html.erb
<h1>Contact Me</h1>
<form>
  <div class="form-group">
    <label for="name">Name:</label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Your Name">
  </div>

  <div class="form-group">
    <label for="email">Email:</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Your Email">
  </div>

  <div class="form-group">
    <label for="subject">Subject:</label>
    <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject">
  </div>

  <div class="form-group">
    <label for="message">Message:</label>
    <textarea class="form-control" id="message" name="message" rows="5" placeholder="Your Message"></textarea>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<p>Welcome to my page :3</p>

app/views/pages/work.html.erb
<h1>My Work</h1>
<p>No work >:)</p>